version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - production-network

  grafana:
    image: grafana/grafana:8.5.0
    container_name: grafana
    ports:
    - 3000:3000
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
        - grafana_data:/var/lib/grafana
    depends_on:
        - prometheus
    networks:
      - production-network

networks:
  production-network:
    name: production-network
    driver: bridge

volumes:
    grafana_data: {}
