global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Load rules once and periodically evaluate them according to the global
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# scrape configuration
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    scrape_interval: 5s
    scheme: 'http'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'string-consumer-actuator'
    metrics_path: '/consumer/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['string-consumer:8081']
      labels:
        instance: 'consumer'

  - job_name: 'string-producer-actuator'
    metrics_path: '/producer/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['string-producer:8082']